# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{action_throttler}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fred Wu"]
  s.date = %q{2010-08-09}
  s.description = %q{Action Throttler is an easy to use Rails plugin to quickly throttle application actions based on configurable duration and limit.}
  s.email = %q{ifredwu@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "init.rb",
     "install.rb",
     "lib/action_throttler/actions.rb",
     "lib/action_throttler/config.rb",
     "lib/action_throttler/model.rb",
     "lib/tasks/action_throttler.rake",
     "lib/tasks/initializer/action_throttler.rb",
     "lib/tasks/migration/create_action_throttler_logs.rb",
     "lib/tasks/rake_helper.rb",
     "spec/action_throttler_spec.rb",
     "spec/spec_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/fredwu/action_throttler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Action Throttler is an easy to use Rails plugin to quickly throttle application actions based on configurable duration and limit.}
  s.test_files = [
    "spec/action_throttler_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

